districts:
  Central: [central, central delhi]
  Dwarka: [dwarka]
  East: [east, east delhi]
  New Delhi: [new delhi, nd]
  North: [north, north delhi]
  North-East: [north east, north-east, northeast]
  North-West: [north west, north-west, northwest]
  Outer: [outer, outer delhi]
  Outer North: [outer north, outer-north]
  Rohini: [rohini]
  Shahdara: [shahdara]
  South: [south, south delhi]
  South-East: [south east, south-east, southeast]
  South-West: [south west, south-west, southwest]
  West: [west, west delhi]
